VERSION=1.1.0
PACKAGE=zcs-zmpkg
MAINTAINER=Enrico Weigelt <enrico.weigelt@vnc.biz>
SECTION=base
ARCHITECTURE=All
PRIORITY=optional
DESCRIPTION=Zimbra package management system
DISTPREFIX=$(TOPDIR)/dist
DISTDIR=$(DISTPREFIX)/$(PACKAGE)-$(VERSION)
DISTFILE=$(DISTPREFIX)/$(DISTFILENAME)
DISTFILENAME=$(PACKAGE)-$(VERSION).tar.gz
JAVA?=java
JAR?=jar
JAVAC?=javac
IMAGE_ROOT=$(TOPDIR)/image
REDMINE_UPLOAD_URL?=https://redmine.vnc.biz/redmine/
REDMINE_UPLOAD_PROJECT?=zcs-zmpkg
