VERSION=1.1.11
PACKAGE=zcs-zmpkg
MAINTAINER=Enrico Weigelt <enrico.weigelt@vnc.biz>
SECTION=free/zcs-base
ARCHITECTURE=All
PRIORITY=optional
DESCRIPTION=Zimbra package management system
REDMINE_UPLOAD_URL?=https://redmine.vnc.biz/redmine/
REDMINE_UPLOAD_PROJECT?=zcs-zmpkg
