#!/bin/bash

err() {
	echo "$*" >&2
	ERROR=1
}

FORBIDDEN_SOURCE_FILES="
	json-minified.js
	bootstrap.js
	examples.js
	ext-all.js
	ext-all.css
"

if [ -d lib ]; then
	find lib -name "*.jar" -type f | ( \
		while read r ; do err "Forbidden binary jar file in zimlet: $r" ; done )
fi

for i in $FORBIDDEN_SOURCE_FILES ; do
	if [ -f src/$i ]; then
		err "Forbidden 3rdparty source file: src/$i"
	fi
done

if [ "$ERROR" ]; then
	exit 99
else
	exit 0
fi
