#!/bin/bash

ME="$0"

err() {
	echo "$ME: $*" >&2
	exit 1
}

## only want to run as unprivileged user
[ `whoami` == 'root' ] && err "dont wanna run as root"

ZIMBRA_ROOT=$HOME

dpkg_init() {
	mkdir -p \
		$ZIMBRA_ROOT/var/lib/dpkg			\
		$ZIMBRA_ROOT/var/lib/dpkg/updates		\
		$ZIMBRA_ROOT/var/lib/dpkg/triggers	\
		$ZIMBRA_ROOT/var/lib/dpkg/info		\
		$ZIMBRA_ROOT/var/log			\
		$ZIMBRA_ROOT/.tmp				\

	touch	\
		$ZIMBRA_ROOT/var/lib/dpkg/status	\
		$ZIMBRA_ROOT/var/lib/dpkg/available

	for i in start-stop-daemon ldconfig ; do
		(echo "#!/bin/bash" ; echo "exit 0" ) > $ZIMBRA_ROOT/.tmp/$i
		chmod +x $ZIMBRA_ROOT/.tmp/$i
	done
}

dpkg_call() {
	dpkg_init
	PATH="$ZIMBRA_ROOT/.tmp:$PATH" dpkg --root=$ZIMBRA_ROOT --log=$ZIMBRA_ROOT/var/log/dpkg.log "$@"
}

zmpkg_help() {
	echo "$ME install <deb-file-name>      install a package file"
	echo "$ME remove <package-name>        remove a package"
	echo "$ME list                         list installed packages"
	echo "$ME redeploy                     deploy zimlets that haven't been deployed yet (due interruption)"
	exit 1
}

zmpkg_deploy_zimlets() {
	if [ -d "$ZIMBRA_ROOT/zimlets-install" ]; then
		for zimlet in `find $ZIMBRA_ROOT/zimlets-install -name "*.zip" 2>/dev/null` ; do
			echo "Deploying zimlet: $zimlet"
			$ZIMBRA_ROOT/bin/zmzimletctl deploy "$zimlet" && rm -f "$zimlet"
		done
		for script in `find $ZIMBRA_ROOT/zimlets-scripts -name "post-install.sh" 2>/dev/null` ; do
			echo "Running post-install script: $script"
			(
				DIRNAME=`dirname "$script"`
				SCRIPTNAME=`basename "$script"`
				cd $DIRNAME && ./$SCRIPTNAME && rm -f $SCRIPTNAME
			)
		done
		find $ZIMBRA_ROOT/zimlets-install -type d -exec "rmdir" "{}" ";" 2>/dev/null
		find $ZIMBRA_ROOT/zimlets-scripts -type d -exec "rmdir" "{}" ";" 2>/dev/null
	fi
}

zmpkg_install() {
	[ "$1" ] || zmpkg_help
	dpkg_call -i "$*" && zmpkg_deploy_zimlets
}

zmpkg_list() {
	dpkg_call -l
}

zmpkg_remove() {
	dpkg_call -r "$@"
}

case "$1" in
	install)
		shift
		zmpkg_install "$@"
	;;
	list)
		shift
		zmpkg_list "$@"
	;;
	remove)
		shift
		zmpkg_remove "$@"
	;;
	redeploy)
		shift
		zmpkg_deploy_zimlets "$@"
	;;
	*)
		zmpkg_help
	;;
esac
