#!/bin/bash

ME="$0"

err() {
	echo "$ME: $*" >&2
	exit 1
}

log() {
	echo "$*" >&2
}

## only want to run as unprivileged user
[ `whoami` == 'root' ] && err "dont wanna run as root"

ZIMBRA_ROOT=$HOME

dpkg_init() {
	mkdir -p \
		$ZIMBRA_ROOT/var/lib/dpkg		\
		$ZIMBRA_ROOT/var/lib/dpkg/updates	\
		$ZIMBRA_ROOT/var/lib/dpkg/triggers	\
		$ZIMBRA_ROOT/var/lib/dpkg/info		\
		$ZIMBRA_ROOT/var/log			\
		$ZIMBRA_ROOT/.tmp			|| err "permission problem. cannot access package database"

	touch	\
		$ZIMBRA_ROOT/var/lib/dpkg/status	\
		$ZIMBRA_ROOT/var/lib/dpkg/available	|| err "permission problem. cannot access package database"
}

dpkg_call() {
	dpkg_init
	export PATH="$PATH:/sbin:/usr/sbin"
#	older dpkg (eg. 1.5.x, which is in ubuntu 10.x) dont support that
#	fakeroot dpkg --force-not-root --foreign-architecture All --root=$ZIMBRA_ROOT --log=$ZIMBRA_ROOT/var/log/dpkg.log "$@"
	fakeroot dpkg --force-not-root --force-architecture --root=$ZIMBRA_ROOT --log=$ZIMBRA_ROOT/var/log/dpkg.log "$@"
}

zmpkg_help() {
	echo "$ME install <deb-file-name>         install a package file"
	echo "$ME remove <package-name>           remove a package"
	echo "$ME list                            list installed packages"
	echo "$ME redeploy                        deploy zimlets that haven't been deployed yet (due interruption)"
	echo "$ME check-installed <package-name>  check whether package with given name is installed (for scripting use)"
	echo "$ME devel-init <zimbra-root>        initial local development environment (using given zimbra installation)"
	echo "$ME dpkg <...>                      direct dpkg call"
	exit 1
}

file_md5() {
	md5sum "$1" | sed -e 's~ .*~~'
}

run_sql() {
	$ZIMBRA_ROOT/bin/mysql < $1
}

need_to_deploy() {
	local zimlet="$1"
	local deployed_md5=`cat "$zimlet.deployed" 2>/dev/null`
	local install_md5=`file_md5 "$zimlet" 2>/dev/null`
	if [ "$deployed_md5" != "$install_md5" ]; then
		return 0
	else
		return 1
	fi
}

mark_deployed() {
	file_md5 "$1" > "$1.deployed"
}

zmpkg_deploy_zimlets() {
	## undeploy remove zimlets
	for statfile in `find $ZIMBRA_ROOT/zimlets-install -name "*.zip.deployed" 2>/dev/null` ; do
		local archive=`echo "$statfile" | sed -e 's~.deployed$~~'`
		local zimlet=`echo "$archive" | sed -e 's~.*/~~; s~.zip$~~'`
		if [ ! -f "$archive" ]; then
			log "Undeploying removed zimlet: $zimlet"
			$ZIMBRA_ROOT/bin/zmzimletctl undeploy "$zimlet" && rm -f $statfile
		fi
	done

	## run sql scripts
	for sqlfile in `find $ZIMBRA_ROOT/zimlets-install -name "mailboxd-db-schema.sql" 2>/dev/null` ; do
		if need_to_deploy $sqlfile ]; then
			log "Deploying sql file: $sqlfile"
			run_sql $sqlfile && mark_deployed $sqlfile
		fi
	done

	## deploy or redeploy zimlets
	for zimlet in `find $ZIMBRA_ROOT/zimlets-install -name "*.zip" 2>/dev/null` ; do
		if need_to_deploy "$zimlet" ; then
			log "Deploying zimlet: $zimlet"
			$ZIMBRA_ROOT/bin/zmzimletctl deploy "$zimlet" && mark_deployed "$zimlet"
		fi
	done

	## run post-install scripts
	for scriptfile in `find $ZIMBRA_ROOT/zimlets-install -name "post-install.sh" 2>/dev/null` ; do
		if need_to_deploy $scriptfile ; then
			log "Running post-install script: $scriptfile"
			$scriptfile && mark_deployed $scriptfile
		fi
	done

	## remove stale post-install markers
	for marker in `find $ZIMBRA_ROOT/zimlets-install -name "post-install.sh.deployed" 2>/dev/null` ; do
		local orig=`echo "$marker" | sed -e 's~\.deployed$~~'`
		if [ ! -f "$orig" ]; then
			log "Removing old post-install marker: $orig"
			rm -f "$marker"
		fi
	done

	## removed empty directories
	find $ZIMBRA_ROOT/zimlets-install -type d -exec "rmdir" "{}" ";" 2>/dev/null
	find $ZIMBRA_ROOT/zimlets-scripts -type d -exec "rmdir" "{}" ";" 2>/dev/null
	return 0
}

zmpkg_install() {
	[ "$1" ] || zmpkg_help
	dpkg_call -i "$@" && zmpkg_deploy_zimlets
}

zmpkg_list() {
	dpkg_call -l "$@" | sed -e 's~:All ~     ~'
}

## fixme should support versioning
zmpkg_check_installed() {
	pkglist=`echo "$*" | sed -e 's~,~ ~g'`
	for i in $pkglist ; do
		if [ "$i" != "__NONE__" ]; then
			if ! ( dpkg_call -s "$i" || dpkg_call -s "$i:All" ) 2>/dev/null >/dev/null; then
				err "missing dependency $i"
				exit 1
			fi
		fi
	done
	exit 0
}

zmpkg_remove() {
	local l=""
	local i
	for i in "$@" ; do
		i=`echo "$i" | sed -e 's~:All~~'`
		l="$l $i:All"
	done
	dpkg_call -r $l
	zmpkg_deploy_zimlets
}

zmpkg_devinit() {
	if [ ! "$1" ]; then
		echo "$0 devel-init <zimbra-root>"
		exit 2
	fi
	local ORIGINAL_ZIMBRA_ROOT="$1"

	## global libdir
	local dirlist="lib/jars jetty/lib jetty/lib/ext jetty/lib/naming jetty/lib/plus jetty/lib/jsp-2.1"
	for i in $dirlist ; do
		mkdir -p $ZIMBRA_ROOT/$i || err "failed to create $ZIMBRA_ROOT/$i"
		(
			cd $ZIMBRA_ROOT/$i || err "failed to create $ZIMBRA_ROOT/$i"
			for i in $ORIGINAL_ZIMBRA_ROOT/$i/*.jar ; do
				ln -sf $i
			done
		)
	done

	## user frontend web container
	local user_lib="mailboxd/webapps/zimbra/WEB-INF/lib"
	mkdir -p $ZIMBRA_ROOT/$user_lib
	(
		cd $ZIMBRA_ROOT/$user_lib
		for i in $ORIGINAL_ZIMBRA_ROOT/$user_lib/*.jar ; do
			ln -sf $i
		done
	)

	## admin backend web containr
	local admin_lib="mailboxd/webapps/zimbraAdmin/WEB-INF/lib"
	mkdir -p $ZIMBRA_ROOT/$admin_lib
	(
		cd $ZIMBRA_ROOT/$admin_lib
		for i in $ORIGINAL_ZIMBRA_ROOT/$admin_lib/*.jar ; do
			ln -sf $i
		done
	)

	## service web containr
	local service_lib="mailboxd/webapps/service/WEB-INF/lib"
	mkdir -p $ZIMBRA_ROOT/$service_lib
	(
		cd $ZIMBRA_ROOT/$service_lib
		for i in $ORIGINAL_ZIMBRA_ROOT/$service_lib/*.jar ; do
			ln -sf $i
		done
	)
}

case "$1" in
	install)
		shift
		zmpkg_install "$@"
	;;
	list)
		shift
		zmpkg_list "$@"
	;;
	remove)
		shift
		zmpkg_remove "$@"
	;;
	redeploy)
		shift
		zmpkg_deploy_zimlets "$@"
	;;
	check-installed)
		shift
		zmpkg_check_installed "$@"
	;;
	devel-init)
		shift
		zmpkg_devinit "$@"
	;;
	dpkg)
		shift
		dpkg_call "$@"
	;;
	*)
		zmpkg_help
	;;
esac
